### ISSUE TITLE
Stale Cached Response on GET

### ISSUE THREAD

**Issue by shakram02** [r4fek/django-cassandra-engine#145] opened 2021-03-10 06:53 UTC
When I `POST` a model to a `ModelViewSet` and then retrieve all objects via a `GET` afterwards I get a stale cached response without the new `POST`ed object. Does `django-cassandra-engine` perform any caching? If I restart the server however it brings the latest data correctly.

I checked Cassandra logs and I found no queries are made when the cached response is returned. I'm actually not sure whether this is because `django-cassandra-engine` or the driver or DRF. Any pointers would be helpful.

I'm already using `never_cache` in the `ModelViewSet`

```python
class SensorReadingViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows sensor readings to be viewed or edited.
    """
    queryset = SensorReading.objects.all()
    serializer_class = SensorReadingSerializer

    @method_decorator(never_cache)
    def list(self, request, *args, **kwargs):
        return super().list(request, *args, **kwargs)
```

**Comment by r4fek** [comment] 2021-05-20 10:00
Have you tried using `get_queryset` method instead of `queryset` variable?

**Comment by r4fek** [comment] 2021-06-10 14:15
I couldn't reproduce it, so closing.

**Closed by r4fek** 2021-06-10 14:15 UTC
